# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
  - name: Questions and Discussions
    url: https://github.com/crazy-max/diun/discussions/new
    about: Use Github Discussions to ask questions and/or open discussion topics.
