db:
  path: diun.db

watch:
  workers: 100
  schedule: "*/30 * * * *"
  first_check_notif: false

notif:
  mail:
    enable: false
    host: localhost
    port: 25
    ssl: false
    insecure_skip_verify: false
    username:
    username_file:
    password:
    password_file:
    from:
    to:
  slack:
    enable: false
    webhook_url: https://hooks.slack.com/services/ABCD12EFG/HIJK34LMN/01234567890abcdefghij
  webhook:
    enable: false
    endpoint: http://webhook.foo.com/sd54qad89azd5a
    method: GET
    headers:
      Content-Type: application/json
      Authorization: Token123456
    timeout: 10

regopts:
  someregopts:
    timeout: 5
  bintrayoptions:
    username: foo
    password: bar
  sensitive:
    username_file: /run/secrets/username
    password_file: /run/secrets/password

providers:
  docker:
    standalone:
      watch_by_default: true
      watch_stopped: true
  swarm:
    local_swarm:
      watch_by_default: true
  static:
    - name: docker.io/crazymax/nextcloud:latest
      regopts_id: someregopts
    - name: crazymax/swarm-cronjob
      watch_repo: true
      include_tags:
        - ^1\.2\..*
    - name: jfrog-docker-reg2.bintray.io/jfrog/artifactory-oss:4.0.0
      regopts_id: bintrayoptions
    - name: docker.bintray.io/jfrog/xray-server:2.8.6
      watch_repo: true
      max_tags: 50
    - name: quay.io/coreos/hyperkube
    - name: docker.io/portainer/portainer
      watch_repo: true
      max_tags: 10
      include_tags:
        - ^(0|[1-9]\d*)\..*
    - name: traefik
      watch_repo: true
    - name: alpine
      os: linux
      arch: arm64v8
    - name: docker.io/graylog/graylog:3.2.0
    - name: jacobalberty/unifi:5.9
    - name: quay.io/coreos/hyperkube:v1.1.7-coreos.1
    - name: crazymax/ddns-route53
      watch_repo: true
      include_tags:
        - ^1\..*
